/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author GUSTAVO
 */
public class Gerenciar_dentistas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gerenciar_dentistas
     */
    public Gerenciar_dentistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_cancelar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gd_campo_pesquisa1 = new javax.swing.JTextField();
        bt_pesquisar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bt_cancelar2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        gd_cro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gd_nome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gd_rg = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        gd_nascimento = new javax.swing.JFormattedTextField();
        gd_cpf = new javax.swing.JFormattedTextField();
        gd_sexo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        bt_pesquisa2 = new javax.swing.JButton();
        gd_campo_pesquisa2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        gd_facebook = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gd_email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gd_celular = new javax.swing.JFormattedTextField();
        gd_skype = new javax.swing.JTextField();
        gd_telefone = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        gd_rua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        gd_complemento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        gd_municipio = new javax.swing.JTextField();
        gd_numero = new javax.swing.JFormattedTextField();
        gd_bairro = new javax.swing.JTextField();
        bt_excluir = new javax.swing.JButton();
        bt_alterar = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Dentistas");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icones/Physician 48.png"))); // NOI18N
        jLabel2.setText("Gerenciar Dentistas");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "Email", "CRO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bt_cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icones/cancel16.png"))); // NOI18N
        bt_cancelar1.setText("Cancelar");
        bt_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelar1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        bt_pesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icones/search16.png"))); // NOI18N
        bt_pesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisar1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(gd_campo_pesquisa1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bt_pesquisar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(bt_cancelar1)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bt_cancelar1)
                    .add(jLabel1)
                    .add(gd_campo_pesquisa1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bt_pesquisar1))
                .add(7, 7, 7)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pesquisar", jPanel1);

        bt_cancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icones/cancel16.png"))); // NOI18N
        bt_cancelar2.setText("Cancelar");
        bt_cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelar2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Pessoais"));

        gd_cro.setEnabled(false);

        jLabel6.setText("Sexo:");

        jLabel5.setText("RG:");

        jLabel4.setText("CPF:");

        gd_nome.setEnabled(false);

        jLabel7.setText("Nome:");

        gd_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        gd_rg.setEnabled(false);

        jLabel18.setText("CRO");

        gd_nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        gd_nascimento.setEnabled(false);

        gd_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        gd_cpf.setEnabled(false);

        gd_sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femninio" }));
        gd_sexo.setEnabled(false);
        gd_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gd_sexoActionPerformed(evt);
            }
        });

        jLabel8.setText("Data de Nascimento:");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(gd_nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 431, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(gd_sexo, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel4)
                                .add(18, 18, 18)
                                .add(gd_cpf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(gd_nascimento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(gd_rg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel18)
                                .add(18, 18, 18)
                                .add(gd_cro)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(gd_nome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel18)
                        .add(gd_cro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel4)
                        .add(jLabel5)
                        .add(gd_cpf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(gd_rg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(gd_sexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(gd_nascimento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_pesquisa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icones/search16.png"))); // NOI18N
        bt_pesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisa2ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        gd_facebook.setEnabled(false);

        jLabel9.setText("E-mail:");

        jLabel12.setText("Facebook:");

        jLabel10.setText("Celular:");

        jLabel11.setText("Skype:");

        gd_email.setEnabled(false);

        jLabel13.setText("Telefone:");

        gd_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        gd_celular.setEnabled(false);

        gd_skype.setEnabled(false);

        gd_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        gd_telefone.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel9)
                        .add(18, 18, 18)
                        .add(gd_email))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jLabel11)
                                .add(18, 18, 18)
                                .add(gd_skype))
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jLabel13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(gd_telefone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel12)
                            .add(jLabel10))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(gd_celular)
                            .add(gd_facebook))))
                .add(49, 49, 49))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(gd_email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(jLabel10)
                    .add(gd_telefone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(gd_celular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(gd_skype, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(gd_facebook, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereco"));

        jLabel16.setText("Bairro:");

        jLabel15.setText("Complemento:");

        gd_rua.setEnabled(false);

        jLabel14.setText("Rua:");

        gd_complemento.setEnabled(false);

        jLabel17.setText("Nº:");

        jLabel19.setText("Municipio:");

        gd_municipio.setEnabled(false);

        gd_numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        gd_numero.setEnabled(false);

        gd_bairro.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(jLabel17)
                    .add(jLabel16))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(gd_bairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(gd_numero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(1, 1, 1)
                                .add(jLabel19)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(gd_municipio))
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(jLabel15)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(gd_complemento, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                    .add(gd_rua, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 361, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(gd_rua, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel17)
                            .add(gd_numero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(gd_bairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel16)))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(gd_complemento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel15))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(gd_municipio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel19))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icones/delete16.png"))); // NOI18N
        bt_excluir.setText("Excluir");
        bt_excluir.setEnabled(false);
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icones/edit16.png"))); // NOI18N
        bt_alterar.setText("Alterar");
        bt_alterar.setEnabled(false);
        bt_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarActionPerformed(evt);
            }
        });

        bt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icones/accept-female-user16.png"))); // NOI18N
        bt_salvar.setText("Salvar");
        bt_salvar.setEnabled(false);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(gd_campo_pesquisa2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bt_pesquisa2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(bt_salvar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bt_excluir)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bt_alterar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bt_cancelar2))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(0, 0, Short.MAX_VALUE)))
                .add(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(gd_campo_pesquisa2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(bt_pesquisa2)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(bt_cancelar2)
                        .add(bt_excluir)
                        .add(bt_alterar)
                        .add(bt_salvar)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gerenciar", jPanel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 536, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelar1ActionPerformed
        dispose();
    }//GEN-LAST:event_bt_cancelar1ActionPerformed

    private void bt_pesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisar1ActionPerformed
        

        
    }//GEN-LAST:event_bt_pesquisar1ActionPerformed

    private void bt_pesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisa2ActionPerformed
        if(!this.gd_campo_pesquisa2.getText().equals("")){
            try{
                String id_result= "";
                Connection con = new Banco().getConnection();
                
                String sql = "SELECT * FROM DENTISTA WHERE id='" +this.gd_campo_pesquisa2.getText()+"'";
                String sql2 = "SELECT id FROM DENTISTA WHERE id='" +this.gd_campo_pesquisa2.getText()+"'";
                
                PreparedStatement stmt = con.prepareStatement(sql);
                PreparedStatement stmt2 = con.prepareStatement(sql2);
                
                ResultSet rs = stmt.executeQuery();
                ResultSet rs2 = stmt2.executeQuery();
                while(rs2.next()){
                    id_result = rs2.getString("id");
                }

                if(!this.gd_campo_pesquisa2.equals(id_result) && !id_result.equals("")){
                    while(rs.next()){
                        this.gd_nome.setText(rs.getString("nome"));
                        this.gd_cpf.setText(rs.getString("cpf"));
                        this.gd_rg.setText(rs.getString("rg"));
                        this.gd_cro.setText(rs.getString("cro"));
                        this.gd_sexo.setSelectedItem(rs.getString("sexo").toString());
                        this.gd_nascimento.setText(rs.getString("data_nascimento"));
                        this.gd_email.setText(rs.getString("email"));
                        this.gd_telefone.setText(rs.getString("telefone"));
                        this.gd_celular.setText(rs.getString("celular"));
                        this.gd_skype.setText(rs.getString("skype"));
                        this.gd_facebook.setText(rs.getString("facebook"));
                        this.gd_rua.setText(rs.getString("rua"));
                        this.gd_numero.setText(rs.getString("numero"));
                        this.gd_complemento.setText(rs.getString("complemento"));
                        this.gd_bairro.setText(rs.getString("bairro"));
                        this.gd_municipio.setText(rs.getString("municipio"));
                    }

                    stmt.close();
                    stmt2.close();
                    rs.close();
                    rs2.close();
                    con.close();

                    bt_alterar.setEnabled(true);
                    bt_excluir.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null,"Este ID não existe!" , "E R R O ! ", 2);
                    atualizar_campos();
                    bt_alterar.setEnabled(false);
                    bt_excluir.setEnabled(false);
                    this.gd_campo_pesquisa2.setText("");
                }
            }catch(Exception e){
                System.out.println("Problema na hora de pesquisar dentista \n" + e);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Insira um ID para a pesquisa!" , "E R R O ! ", 2);
        }
    }//GEN-LAST:event_bt_pesquisa2ActionPerformed

    private void bt_cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelar2ActionPerformed
        dispose();        
    }//GEN-LAST:event_bt_cancelar2ActionPerformed

    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
        habilitar_campos();
        bt_excluir.setEnabled(false);
        bt_alterar.setEnabled(false);
        bt_salvar.setEnabled(true);
        bt_pesquisa2.setEnabled(false);
        this.gd_campo_pesquisa2.setEnabled(false);
        
    }//GEN-LAST:event_bt_alterarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        JOptionPane.showMessageDialog(null,"Deseja excluir o dentista " + this.gd_nome.getText()+ " ?" , "A T E N Ç Ã O ! ", 2);
        try{
          Connection con = new Banco().getConnection();
          String sql = "DELETE FROM DENTISTA WHERE id='" + this.gd_campo_pesquisa2.getText()+"'";
          PreparedStatement stmt = con.prepareStatement(sql);
          stmt.execute();
          
          stmt.close();
          con.close();
          
          JOptionPane.showMessageDialog(null,"Dentista " + this.gd_nome.getText()+ " excluido com sucesso!" , "A T E N Ç Ã O ! ", 1);
          atualizar_campos();
          bt_alterar.setEnabled(false);
          bt_excluir.setEnabled(false);
          this.gd_campo_pesquisa2.setText("");
          
        }catch(Exception e){
            System.out.println("Problema ao exlcuir dentista! \n" +e);
        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
       try{
           Connection con = new Banco().getConnection();
           String sql = "UPDATE DENTISTA SET nome='" + this.gd_nome.getText()+"', cpf='" + this.gd_cpf.getText()+"', rg='" + this.gd_rg.getText()+"', cro='" + this.gd_cro.getText()+"', sexo='" + this.gd_sexo.getSelectedItem().toString() +"', data_nascimento='" 
                   + this.gd_nascimento.getText()+"', email='" + this.gd_email.getText()+"',  telefone='" + this.gd_telefone.getText()+"', celular='" + this.gd_celular.getText()+"', skype='" + this.gd_skype.getText()+"', facebook='" 
                   + this.gd_facebook.getText()+"', rua='" + this.gd_rua.getText()+"', numero='" + this.gd_numero.getText()+"',  complemento='" + this.gd_complemento.getText()+"', bairro='" + this.gd_bairro.getText()+"', municipio='" + this.gd_municipio.getText()+"' WHERE id='"+this.gd_campo_pesquisa2.getText()+"'";
           PreparedStatement stmt = con.prepareStatement(sql);
           stmt.execute();

           stmt.close();
           con.close();
           
           JOptionPane.showMessageDialog(null,"Informações atualizadas!" , "A T E N Ç Ã O ! ", 1);
           desabilitar_campos();
           bt_salvar.setEnabled(false);
           bt_excluir.setEnabled(true);
           bt_alterar.setEnabled(true);
           bt_pesquisa2.setEnabled(true);
           this.gd_campo_pesquisa2.setEnabled(true);
        } catch(Exception e){
           System.out.println("Erro ao atualizar dentista! \n" + e);
       }
        
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void gd_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gd_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gd_sexoActionPerformed

    public void habilitar_campos(){
                this.gd_nome.setEnabled(true);
                this.gd_cpf.setEnabled(true);
                this.gd_rg.setEnabled(true);
                this.gd_cro.setEnabled(true);
                this.gd_sexo.setEnabled(true);
                this.gd_nascimento.setEnabled(true);
                this.gd_email.setEnabled(true);
                this.gd_telefone.setEnabled(true);
                this.gd_celular.setEnabled(true);
                this.gd_skype.setEnabled(true);
                this.gd_facebook.setEnabled(true);
                this.gd_rua.setEnabled(true);
                this.gd_numero.setEnabled(true);
                this.gd_complemento.setEnabled(true);
                this.gd_bairro.setEnabled(true);
                this.gd_municipio.setEnabled(true);
    }
    public void desabilitar_campos(){
                this.gd_nome.setEnabled(false);
                this.gd_cpf.setEnabled(false);
                this.gd_rg.setEnabled(false);
                this.gd_cro.setEnabled(false);
                this.gd_sexo.setEnabled(false);
                this.gd_nascimento.setEnabled(false);
                this.gd_email.setEnabled(false);
                this.gd_telefone.setEnabled(false);
                this.gd_celular.setEnabled(false);
                this.gd_skype.setEnabled(false);
                this.gd_facebook.setEnabled(false);
                this.gd_rua.setEnabled(false);
                this.gd_numero.setEnabled(false);
                this.gd_complemento.setEnabled(false);
                this.gd_bairro.setEnabled(false);
                this.gd_municipio.setEnabled(false); 
    }
   public void atualizar_campos(){
                this.gd_nome.setText("");
                this.gd_cpf.setText("");
                this.gd_rg.setText("");
                this.gd_cro.setText("");
                this.gd_sexo.setSelectedItem("");
                this.gd_nascimento.setText("");
                this.gd_email.setText("");
                this.gd_telefone.setText("");
                this.gd_celular.setText("");
                this.gd_skype.setText("");
                this.gd_facebook.setText("");
                this.gd_rua.setText("");
                this.gd_numero.setText("");
                this.gd_complemento.setText("");
                this.gd_bairro.setText("");
                this.gd_municipio.setText("");
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_cancelar1;
    private javax.swing.JButton bt_cancelar2;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_pesquisa2;
    private javax.swing.JButton bt_pesquisar1;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JTextField gd_bairro;
    private javax.swing.JTextField gd_campo_pesquisa1;
    private javax.swing.JTextField gd_campo_pesquisa2;
    private javax.swing.JFormattedTextField gd_celular;
    private javax.swing.JTextField gd_complemento;
    private javax.swing.JFormattedTextField gd_cpf;
    private javax.swing.JTextField gd_cro;
    private javax.swing.JTextField gd_email;
    private javax.swing.JTextField gd_facebook;
    private javax.swing.JTextField gd_municipio;
    private javax.swing.JFormattedTextField gd_nascimento;
    private javax.swing.JTextField gd_nome;
    private javax.swing.JFormattedTextField gd_numero;
    private javax.swing.JFormattedTextField gd_rg;
    private javax.swing.JTextField gd_rua;
    private javax.swing.JComboBox gd_sexo;
    private javax.swing.JTextField gd_skype;
    private javax.swing.JFormattedTextField gd_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
