/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS;

/**
 *
 * @author GUSTAVO
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MAin
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        m_sobre = new javax.swing.JMenuItem();
        m_backup = new javax.swing.JMenuItem();
        m_config = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        m_sair = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        m_novDentista = new javax.swing.JMenuItem();
        m_gerDentista = new javax.swing.JMenuItem();
        editMenu1 = new javax.swing.JMenu();
        m_novPaciente = new javax.swing.JMenuItem();
        m_gerPaciente = new javax.swing.JMenuItem();
        editMenu2 = new javax.swing.JMenu();
        m_novConsulta = new javax.swing.JMenuItem();
        m_gerConsulta = new javax.swing.JMenuItem();
        editMenu4 = new javax.swing.JMenu();
        m_novUsuario = new javax.swing.JMenuItem();
        m_gerUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Odontologia");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Arquivo");

        m_sobre.setMnemonic('a');
        m_sobre.setText("Sobre ");
        fileMenu.add(m_sobre);

        m_backup.setMnemonic('s');
        m_backup.setText("Backup");
        fileMenu.add(m_backup);

        m_config.setMnemonic('a');
        m_config.setText("Configurações");
        fileMenu.add(m_config);
        fileMenu.add(jSeparator1);

        m_sair.setMnemonic('x');
        m_sair.setText("Sair");
        m_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_sairActionPerformed(evt);
            }
        });
        fileMenu.add(m_sair);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Dentistas");

        m_novDentista.setMnemonic('t');
        m_novDentista.setText("Novo dentista");
        m_novDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_novDentistaActionPerformed(evt);
            }
        });
        editMenu.add(m_novDentista);

        m_gerDentista.setMnemonic('y');
        m_gerDentista.setText("Gerenciar dentistas");
        m_gerDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_gerDentistaActionPerformed(evt);
            }
        });
        editMenu.add(m_gerDentista);

        menuBar.add(editMenu);

        editMenu1.setMnemonic('e');
        editMenu1.setText("Pacientes");

        m_novPaciente.setMnemonic('t');
        m_novPaciente.setText("Novo paciente");
        m_novPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_novPacienteActionPerformed(evt);
            }
        });
        editMenu1.add(m_novPaciente);

        m_gerPaciente.setMnemonic('y');
        m_gerPaciente.setText("Gerenciar pacientes");
        m_gerPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_gerPacienteActionPerformed(evt);
            }
        });
        editMenu1.add(m_gerPaciente);

        menuBar.add(editMenu1);

        editMenu2.setMnemonic('e');
        editMenu2.setText("Consultas");

        m_novConsulta.setMnemonic('t');
        m_novConsulta.setText("Nova consulta");
        m_novConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_novConsultaActionPerformed(evt);
            }
        });
        editMenu2.add(m_novConsulta);

        m_gerConsulta.setMnemonic('y');
        m_gerConsulta.setText("Consultas");
        editMenu2.add(m_gerConsulta);

        menuBar.add(editMenu2);

        editMenu4.setMnemonic('e');
        editMenu4.setText("Administração");

        m_novUsuario.setMnemonic('y');
        m_novUsuario.setText("Novo usuario");
        editMenu4.add(m_novUsuario);

        m_gerUsuario.setMnemonic('t');
        m_gerUsuario.setText("Gerenciar usuarios");
        editMenu4.add(m_gerUsuario);

        menuBar.add(editMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1424, 795));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void m_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_m_sairActionPerformed

    private void m_novConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_novConsultaActionPerformed
        Nova_consulta t1 = new Nova_consulta();
        t1.setVisible(true);
        desktopPane.add(t1);
        
    }//GEN-LAST:event_m_novConsultaActionPerformed

    private void m_novPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_novPacienteActionPerformed
        Novo_paciente t2 = new Novo_paciente();
        t2.setVisible(true);
        desktopPane.add(t2);
    }//GEN-LAST:event_m_novPacienteActionPerformed

    private void m_novDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_novDentistaActionPerformed
        Novo_dentista t3 = new Novo_dentista();
        t3.setVisible(true);
        desktopPane.add(t3);
    }//GEN-LAST:event_m_novDentistaActionPerformed

    private void m_gerDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_gerDentistaActionPerformed
        Gerenciar_dentistas t4 = new Gerenciar_dentistas();
        t4.setVisible(true);
        desktopPane.add(t4);
    }//GEN-LAST:event_m_gerDentistaActionPerformed

    private void m_gerPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_gerPacienteActionPerformed
        Gerenciar_pacientes t5 = new Gerenciar_pacientes();
        t5.setVisible(true);
        desktopPane.add(t5);
    }//GEN-LAST:event_m_gerPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenu editMenu2;
    private javax.swing.JMenu editMenu4;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem m_backup;
    private javax.swing.JMenuItem m_config;
    private javax.swing.JMenuItem m_gerConsulta;
    private javax.swing.JMenuItem m_gerDentista;
    private javax.swing.JMenuItem m_gerPaciente;
    private javax.swing.JMenuItem m_gerUsuario;
    private javax.swing.JMenuItem m_novConsulta;
    private javax.swing.JMenuItem m_novDentista;
    private javax.swing.JMenuItem m_novPaciente;
    private javax.swing.JMenuItem m_novUsuario;
    private javax.swing.JMenuItem m_sair;
    private javax.swing.JMenuItem m_sobre;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
